app/base/models.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/error-<error>')
def route_errors(error):
    return render_template('errors/{}.html'.format(error))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'login/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'login/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/create_user', methods=['GET', 'POST'])
def create_user():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'login/register.html', msg='Username already registered', form=create_account_form)

        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'login/register.html', msg='Email already registered', form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'login/register.html', msg='User created please <a href="/login">login</a>', form=create_account_form)

    else:
        return render_template( 'login/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('errors/404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('errors/500.html'), 500

app/base/templates/base-site-fullscreen.html
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>
      Flask Dashboard Material Admin - {% block title %}{% endblock %} | AppSeed
  </title>

  <!-- plugins:css -->
  <link rel="stylesheet" href="/static/assets/vendors/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="/static/assets/vendors/css/vendor.bundle.base.css">
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <link rel="stylesheet" href="/static/assets/vendors/flag-icon-css/css/flag-icon.min.css">
  <link rel="stylesheet" href="/static/assets/vendors/jvectormap/jquery-jvectormap.css">
  <!-- End plugin css for this page -->
  <!-- Layout styles -->
  <link rel="stylesheet" href="/static/assets/css/demo/style.css">
  <!-- End layout styles -->
  <link rel="shortcut icon" href="/static/assets/images/favicon.png" />

  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body>
<script src="/static/assets/js/preloader.js"></script>

<div class="body-wrapper">

    <div class="main-wrapper">

        {% block content %}{% endblock content %}

    </div>

</div>

{% include 'site_template/scripts.html' %}

{% block javascripts %}{% endblock javascripts %}

</body>
</html>

app/base/templates/base-site.html
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>
      Flask Dashboard Material Admin - {% block title %}{% endblock %} | AppSeed
  </title>

  <!-- plugins:css -->
  <link rel="stylesheet" href="/static/assets/vendors/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="/static/assets/vendors/css/vendor.bundle.base.css">
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <link rel="stylesheet" href="/static/assets/vendors/flag-icon-css/css/flag-icon.min.css">
  <link rel="stylesheet" href="/static/assets/vendors/jvectormap/jquery-jvectormap.css">
  <!-- End plugin css for this page -->
  <!-- Layout styles -->
  <link rel="stylesheet" href="/static/assets/css/demo/style.css">
  <!-- End layout styles -->
  <link rel="shortcut icon" href="/static/assets/images/favicon.png" />

  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body>
<script src="/static/assets/js/preloader.js"></script>

<div class="body-wrapper">

    {% include 'site_template/sidebar.html' %}

    <!-- partial -->
    <div class="main-wrapper mdc-drawer-app-content">

      {% include 'site_template/navigation.html' %}

      <!-- partial -->
      <div class="page-wrapper mdc-toolbar-fixed-adjust">
        
        <main class="content-wrapper">

          {% block content %}{% endblock content %}

        </main>

        {% include 'site_template/footer.html' %}    

      </div>
    </div>
  </div>

  {% include 'site_template/scripts.html' %}

  {% block javascripts %}{% endblock javascripts %}

</body>
</html>

app/base/templates/login/login.html
{% extends "base-site-fullscreen.html" %}

{% block title %} Login {% endblock %} 

{% block content %}
      
    <div class="page-wrapper full-page-wrapper d-flex align-items-center justify-content-center">
      <main class="auth-page">
        <div class="mdc-layout-grid">
          <div class="mdc-layout-grid__inner">
            <div class="stretch-card mdc-layout-grid__cell--span-4-desktop mdc-layout-grid__cell--span-1-tablet"></div>
            <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-4-desktop mdc-layout-grid__cell--span-6-tablet">
              <div class="mdc-card">
                <div class="text-center">
                  <h1>
                    <a href="https://appseed.us/admin-dashboards/flask-dashboard-admin-material" >Flask Dashboard Material Admin</a>
                  </h1>
                  <br />
                  <h5>
                        {% if msg %}
                            {{ msg | safe }}
                        {% else %}
                        <span>
                          Use default credentials: test / pass
                          <br />
                          OR <a href={{ url_for('base_blueprint.create_user') }} >create your own user</a>
                        </span>
                        {% endif %}               
                  </h5>
                </div>
                  
                <form role="form" method="post" action="">

                  {{ form.hidden_tag() }} 

                  <div class="mdc-layout-grid">
                    <div class="mdc-layout-grid__inner">
                      <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                        <div class="mdc-text-field w-100">
                          {{ form.username(placeholder="Username", class="form-control mdc-text-field__input") }}
                          <div class="mdc-line-ripple"></div>
                          <label for="text-field-hero-input" class="mdc-floating-label">Username</label>
                        </div>
                      </div>
                      <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                        <div class="mdc-text-field w-100">
                          {{ form.password(placeholder="Password", class="mdc-text-field__input", type="password") }}
                          <div class="mdc-line-ripple"></div>
                          <label for="text-field-hero-input" class="mdc-floating-label">Password</label>
                        </div>
                      </div>
                      <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
                        <div class="mdc-form-field">
                          <div class="mdc-checkbox">
                            <input type="checkbox"
                                    class="mdc-checkbox__native-control"
                                    id="checkbox-1"/>
                            <div class="mdc-checkbox__background">
                              <svg class="mdc-checkbox__checkmark"
                                    viewBox="0 0 24 24">
                                <path class="mdc-checkbox__checkmark-path"
                                      fill="none"
                                      d="M1.73,12.91 8.1,19.28 22.79,4.59"/>
                              </svg>
                              <div class="mdc-checkbox__mixedmark"></div>
                            </div>
                          </div>
                          <label for="checkbox-1">Remember me</label>
                        </div>
                      </div>
                      <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop d-flex align-items-center justify-content-end">
                        <a href={{ url_for('base_blueprint.create_user') }} >Register</a>
                      </div>
                      <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                        <button type="submit" name="login" class="mdc-button mdc-button--raised w-100">
                          Login
                        </button>

                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <div class="stretch-card mdc-layout-grid__cell--span-4-desktop mdc-layout-grid__cell--span-1-tablet"></div>
          </div>
        </div>
      </main>
    </div>

{% endblock content %}

app/base/templates/site_template/navigation.html
    <!-- partial:partials/_navbar.html -->
    <header class="mdc-top-app-bar">

        <div class="mdc-top-app-bar__row">
            <div class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
            <button class="material-icons mdc-top-app-bar__navigation-icon mdc-icon-button sidebar-toggler">menu</button>
            <span class="mdc-top-app-bar__title">Flask Dashboard</span>
            <div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon search-text-field d-none d-md-flex">
                <i class="material-icons mdc-text-field__icon">search</i>
                <input class="mdc-text-field__input" id="text-field-hero-input">
                <div class="mdc-notched-outline">
                <div class="mdc-notched-outline__leading"></div>
                <div class="mdc-notched-outline__notch">
                    <label for="text-field-hero-input" class="mdc-floating-label">Search..</label>
                </div>
                <div class="mdc-notched-outline__trailing"></div>
                </div>
            </div>
            </div>
            <div class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end mdc-top-app-bar__section-right">
            <div class="menu-button-container menu-profile d-none d-md-block">
                <button class="mdc-button mdc-menu-button">
                <span class="d-flex align-items-center">
                    <span class="figure">
                    <img src="/static/assets/images/faces/face1.jpg" alt="user" class="user">
                    </span>
                    <span class="user-name">
                    {{ current_user.username }}
                    </span>
                </span>
                </button>
                <div class="mdc-menu mdc-menu-surface" tabindex="-1">
                <ul class="mdc-list" role="menu" aria-hidden="true" aria-orientation="vertical">
                    <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail item-thumbnail-icon-only">
                        <i class="mdi mdi-account-edit-outline text-primary"></i>
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                        <h6 class="item-subject font-weight-normal">Edit profile</h6>
                    </div>
                    </li>
                    <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail item-thumbnail-icon-only">
                        <i class="mdi mdi-settings-outline text-primary"></i>                      
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                        <h6 class="item-subject font-weight-normal">
                        <a href={{ url_for('base_blueprint.logout') }} >Logout</a>
                        </h6>
                    </div>
                    </li>
                </ul>
                </div>
            </div>
            <div class="divider d-none d-md-block"></div>
            <div class="menu-button-container d-none d-md-block">
                <button class="mdc-button mdc-menu-button">
                <i class="mdi mdi-settings"></i>
                </button>
                <div class="mdc-menu mdc-menu-surface" tabindex="-1">
                <ul class="mdc-list" role="menu" aria-hidden="true" aria-orientation="vertical">
                    <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail item-thumbnail-icon-only">
                        <i class="mdi mdi-alert-circle-outline text-primary"></i>
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                        <h6 class="item-subject font-weight-normal">Settings</h6>
                    </div>
                    </li>
                    <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail item-thumbnail-icon-only">
                        <i class="mdi mdi-progress-download text-primary"></i>                      
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                        <h6 class="item-subject font-weight-normal">Update</h6>
                    </div>
                    </li>
                </ul>
                </div>
            </div>
            <div class="menu-button-container">
                <button class="mdc-button mdc-menu-button">
                <i class="mdi mdi-bell"></i>
                </button>
                <div class="mdc-menu mdc-menu-surface" tabindex="-1">
                <h6 class="title"> <i class="mdi mdi-bell-outline mr-2 tx-16"></i> Notifications</h6>
                <ul class="mdc-list" role="menu" aria-hidden="true" aria-orientation="vertical">
                    <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail item-thumbnail-icon">
                        <i class="mdi mdi-email-outline"></i>
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                        <h6 class="item-subject font-weight-normal">You received a new message</h6>
                        <small class="text-muted"> 6 min ago </small>
                    </div>
                    </li>
                    <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail item-thumbnail-icon">
                        <i class="mdi mdi-account-outline"></i>                      
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                        <h6 class="item-subject font-weight-normal">New user registered</h6>
                        <small class="text-muted"> 15 min ago </small>
                    </div>
                    </li>
                    <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail item-thumbnail-icon">
                        <i class="mdi mdi-alert-circle-outline"></i>
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                        <h6 class="item-subject font-weight-normal">System Alert</h6>
                        <small class="text-muted"> 2 days ago </small>
                    </div>
                    </li> 
                    <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail item-thumbnail-icon">
                        <i class="mdi mdi-update"></i>
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                        <h6 class="item-subject font-weight-normal">You have a new update</h6>
                        <small class="text-muted"> 3 days ago </small>
                    </div>
                    </li> 
                </ul>
                </div>
            </div>
            <div class="menu-button-container">
                <button class="mdc-button mdc-menu-button">
                <i class="mdi mdi-email"></i>
                <span class="count-indicator">
                    <span class="count">3</span>
                </span>
                </button>
                <div class="mdc-menu mdc-menu-surface" tabindex="-1">
                <h6 class="title"><i class="mdi mdi-email-outline mr-2 tx-16"></i> Messages</h6>
                <ul class="mdc-list" role="menu" aria-hidden="true" aria-orientation="vertical">
                    <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail">
                        <img src="/static/assets/images/faces/face4.jpg" alt="user">
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                        <h6 class="item-subject font-weight-normal">Mark send you a message</h6>
                        <small class="text-muted"> 1 Minutes ago </small>
                    </div>
                    </li>
                    <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail">
                        <img src="/static/assets/images/faces/face2.jpg" alt="user">
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                        <h6 class="item-subject font-weight-normal">Cregh send you a message</h6>
                        <small class="text-muted"> 15 Minutes ago </small>
                    </div>
                    </li>
                    <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail">
                        <img src="/static/assets/images/faces/face3.jpg" alt="user">
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                        <h6 class="item-subject font-weight-normal">Profile picture updated</h6>
                        <small class="text-muted"> 18 Minutes ago </small>
                    </div>
                    </li>                
                </ul>
                </div>
            </div>
            <div class="menu-button-container d-none d-md-block">
                <button class="mdc-button mdc-menu-button">
                <i class="mdi mdi-arrow-down-bold-box"></i>
                </button>
                <div class="mdc-menu mdc-menu-surface" tabindex="-1">
                <ul class="mdc-list" role="menu" aria-hidden="true" aria-orientation="vertical">
                    <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail item-thumbnail-icon-only">
                        <i class="mdi mdi-lock-outline text-primary"></i>
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                        <h6 class="item-subject font-weight-normal">Lock screen</h6>
                    </div>
                    </li>
                    <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail item-thumbnail-icon-only">
                        <i class="mdi mdi-logout-variant text-primary"></i>                      
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                        <h6 class="item-subject font-weight-normal">
                        <a href={{ url_for('base_blueprint.logout') }} >Logout</a>
                        </h6>
                    </div>
                    </li>
                </ul>
                </div>
            </div>
            </div>
        </div>

    </header>
 

app/base/templates/site_template/scripts.html
  <script src="/static/assets/vendors/js/vendor.bundle.base.js"></script>

  <script src="/static/assets/js/material.js"></script>
  <script src="/static/assets/js/misc.js"></script>

app/base/templates/site_template/sidebar.html
        <!-- partial:partials/_sidebar.html -->
        <aside class="mdc-drawer mdc-drawer--dismissible mdc-drawer--open">

            <div class="mdc-drawer__header">
              <a href="/" class="brand-logo">
                <img src="/static/assets/images/logo.svg" alt="logo">
              </a>
            </div>
            <div class="mdc-drawer__content">
              <div class="user-info">
                <p class="name">{{ current_user.username }}</p>
                <p class="email">{{ current_user.email }}</p>
              </div>
              <div class="mdc-list-group">
                <nav class="mdc-list mdc-drawer-menu">
                  <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="/">
                      <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">home</i>
                      Dashboard
                    </a>
                  </div>
                  <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="/ui-forms">
                      <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">track_changes</i>
                      Forms
                    </a>
                  </div>
                  <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-expansion-panel-link" href="#" data-toggle="expansionPanel" data-target="ui-sub-menu">
                      <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">dashboard</i>
                      UI Features
                      <i class="mdc-drawer-arrow material-icons">chevron_right</i>
                    </a>
                    <div class="mdc-expansion-panel" id="ui-sub-menu">
                      <nav class="mdc-list mdc-drawer-submenu">
                        <div class="mdc-list-item mdc-drawer-item">
                          <a class="mdc-drawer-link" href="/ui-buttons">
                            Buttons
                          </a>
                        </div>
                        <div class="mdc-list-item mdc-drawer-item">
                          <a class="mdc-drawer-link" href="/ui-typography">
                            Typography
                          </a>
                        </div>
                      </nav>
                    </div>
                  </div>
                  <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="/ui-basic-tables">
                      <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">grid_on</i>
                      Tables
                    </a>
                  </div>
                  <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="/chartjs">
                      <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">pie_chart_outlined</i>
                      Charts
                    </a>
                  </div>
                  <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-expansion-panel-link" href="#" data-toggle="expansionPanel" data-target="sample-page-submenu">
                      <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">pages</i>
                      Sample Pages
                      <i class="mdc-drawer-arrow material-icons">chevron_right</i>
                    </a>
                    <div class="mdc-expansion-panel" id="sample-page-submenu">
                      <nav class="mdc-list mdc-drawer-submenu">
                        <div class="mdc-list-item mdc-drawer-item">
                          <a class="mdc-drawer-link" href="/page-blank">
                            Blank Page
                          </a>
                        </div>
                        <div class="mdc-list-item mdc-drawer-item">
                          <a class="mdc-drawer-link" href="/page-403">
                            403
                          </a>
                        </div>
                        <div class="mdc-list-item mdc-drawer-item">
                          <a class="mdc-drawer-link" href="/page-404">
                            404
                          </a>
                        </div>
                        <div class="mdc-list-item mdc-drawer-item">
                          <a class="mdc-drawer-link" href="/page-500">
                            500
                          </a>
                        </div>
                        <div class="mdc-list-item mdc-drawer-item">
                          <a class="mdc-drawer-link" href="/create_user">
                            Register
                          </a>
                        </div>
                      </nav>
                    </div>
                  </div>
                  <div class="mdc-list-item mdc-drawer-item">
                    <a class="mdc-drawer-link" href="https://www.bootstrapdash.com/demo/material-admin-free/jquery/documentation/documentation.html" target="_blank">
                      <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">description</i>
                      UI Documentation
                    </a>
                  </div>
                </nav>
              </div>
              <div class="profile-actions">
                <a href="javascript:;">Settings</a>
                <span class="divider"></span>
                <a href={{ url_for('base_blueprint.logout') }} >Logout</a>
              </div>
              <div class="mdc-card premium-card">
                <div class="d-flex align-items-center">
                  <div class="mdc-card icon-card box-shadow-0">
                    <i class="mdi mdi-shield-outline"></i>
                  </div>
                  <div>
                    <p class="mt-0 mb-1 ml-2 font-weight-bold tx-12">Material Admin</p>
                    <p class="mt-0 mb-0 ml-2 tx-10">Flask Dashboard</p>
                  </div>
                </div>
      
                <br />
      
                <a href="https://appseed.us/admin-dashboards/flask-dashboard-material-admin" >
                    <span class="mdc-button mdc-button--raised mdc-button--white">Product Info</span>
                </a>
                
              </div>
            </div>
        
        </aside>
 

          